#!/bin/csh -f
set output = section_uncertainty_PWS_PWS_reloc.eps
set cpt = uncertainty.cpt

# Boundaries
set x1 = -123.6
set x2 = -122.8
set y1 = -55.0
set y2 = 5.0
set Rop = $x1/$x2/$y1/$y2
set Jop = x20.0/0.2

# Locations of arrays
cat << END >> arrays.dat
-123.084354545455 0.5
-122.92866 0.5
-122.969935 0.5
-123.313118181818 0.5
-123.045528571429 0.5
-123.210035714286 0.5
-123.464415384615 0.5
-123.138492857143 0.5
END

gmt psxy arrays.dat -R$Rop -Ba0.25f0.125:"Longitude":/a20f5:"Depth (km)":WeSn -J$Jop -St0.4 -Gblack -Y10 -P -K >! $output

gmt psxy mccrory_2.txt -R$Rop -J$Jop -Wthicker,black -O -K >> $output
gmt psxy preston_2.txt -R$Rop -J$Jop -Wthicker,black,dashed -O -K >> $output

gmt psxy section_sweet_2.txt -R$Rop -J$Jop -Sc0.2 -Gblack -W -O -K >> $output
gmt psxy section_chestler_2.txt -R$Rop -J$Jop -Sc0.2 -Gblack -W -O -K >> $output

gmt psxy section_uncertainty_PWS_PWS_BH_reloc.txt -R$Rop -J$Jop -Ss0.4 -C$cpt -O -K >> $output
gmt psxy section_uncertainty_PWS_PWS_BS_reloc.txt -R$Rop -J$Jop -Sa0.4 -C$cpt -O -K >> $output
gmt psxy section_uncertainty_PWS_PWS_DR_reloc.txt -R$Rop -J$Jop -Si0.4 -C$cpt -O -K >> $output
gmt psxy section_uncertainty_PWS_PWS_GC_reloc.txt -R$Rop -J$Jop -Sc0.4 -C$cpt -O -K >> $output
gmt psxy section_uncertainty_PWS_PWS_PA_reloc.txt -R$Rop -J$Jop -Sd0.4 -C$cpt -O -K >> $output
gmt psxy section_uncertainty_PWS_PWS_TB_reloc.txt -R$Rop -J$Jop -St0.4 -C$cpt -O -K >> $output


# Horizontal line
cat << END >> ground.dat
-123.6 0.0
-122.7 0.0
END

gmt psxy ground.dat -R$Rop -J$Jop -Wthicker -O -K >> $output

gmt psscale -C$cpt -D7.0/-3.0/10/0.5h -O -L -B:"Uncertainty in km": >> $output

rm arrays.dat
rm ground.dat
