#!/bin/csh -f
set output = depth_PWS_PWS.eps
set cpt = depth.cpt

# Boundaries
set x1 = -123.6
set x2 = -122.8
set y1 = 47.7
set y2 = 48.3
set Rop = $x1/$x2/$y1/$y2
set Jop = m-123.2/48.0/25.0

gmt pscoast -R$Rop -J$Jop -Ba0.25f0.125::WESN -W0.1p -G255/255/224 -S224/255/255 -Df -Na -Y10 -P -K >! $output

gmt xyz2grd plate_boundary_P.txt -Gplate_boundary.grd -I0.1 -R$Rop
gmt grdcontour plate_boundary.grd -A2 -J$Jop -R$Rop -O -K >> $output

gmt psxy crosssection_1.txt -R$Rop -J$Jop -Wthicker,black -O -K >> $output
gmt psxy crosssection_2.txt -R$Rop -J$Jop -Wthicker,black -O -K >> $output
gmt psxy crosssection_3.txt -R$Rop -J$Jop -Wthicker,black -O -K >> $output

cat << END >> mytext.dat
-123.55 47.80 A
-122.85 47.93 A'
-123.55 47.90 B
-122.85 48.03 B'
-123.55 48.00 C
-122.85 48.13 C'
END

gmt pstext mytext.dat -R$Rop -J$Jop -F+f15p -O -K >> $output

gmt psxy depth_sweet.txt -R$Rop -J$Jop -Sc0.2 -C$cpt -W -O -K >> $output
gmt psxy depth_chestler.txt -R$Rop -J$Jop -Sc0.2 -C$cpt -W -O -K >> $output

# Locations of arrays
cat << END >> arrays.dat
-123.084354545455 48.0056818181818
-122.92866 47.95728
-122.969935 48.068735
-123.313118181818 48.0059272727273
-123.045528571429 47.9321857142857
-123.210035714286 48.0554071428571
-123.464415384615 48.0549384615385
-123.138492857143 47.9730357142857
END

gmt psxy arrays.dat -R$Rop -J$Jop -St0.4 -Gblack -O -K >> $output

gmt psxy depth_PWS_PWS_BH.txt -R$Rop -J$Jop -Ss0.4 -C$cpt -O -K >> $output
gmt psxy depth_PWS_PWS_BS.txt -R$Rop -J$Jop -Sa0.4 -C$cpt -O -K >> $output
gmt psxy depth_PWS_PWS_DR.txt -R$Rop -J$Jop -Si0.4 -C$cpt -O -K >> $output
gmt psxy depth_PWS_PWS_GC.txt -R$Rop -J$Jop -Sc0.4 -C$cpt -O -K >> $output
gmt psxy depth_PWS_PWS_PA.txt -R$Rop -J$Jop -Sd0.4 -C$cpt -O -K >> $output
gmt psxy depth_PWS_PWS_TB.txt -R$Rop -J$Jop -Sh0.4 -C$cpt -O -K >> $output

gmt psscale -C$cpt -D7.0/-3.0/12/0.5h -O -L -B:"Tremor depth in km": >> $output

rm arrays.dat
rm mytext.dat
